#
# Makefile.mingw
#
# Description: Makefile for win32 (mingw) version of Pidgin pixmaps
#

PIDGIN_TREE_TOP := ../../..
include $(PIDGIN_TREE_TOP)/libpurple/win32/global.mak

datadir = $(PIDGIN_INSTALL_DIR)
include ./Makefile.am

.PHONY: install

install:
	if test '$(pidginemotespix_DATA)'; then \
	  mkdir -p $(pidginemotespixdir); \
	  cp $(pidginemotespix_DATA) $(pidginemotespixdir); \
	fi;

clean:
	@echo There is nothing to do.

